databases:
  - name: sanmon
    databaseName: sanmon
    user: sanmon

services:
  - type: web
    name: sanmon
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sanmon
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false